name: Swift

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v

  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-22.04
    container:
      image: swift:6.0.3-jammy
    steps:
    - uses: actions/checkout@v4
    
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v