name: Swift

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test-macos:
    name: Test on macOS
    runs-on: macos-latest
    strategy:
      matrix:
        swift: ['6.0', '6.0.1', '6.0.2', '6.0.3']
    steps:
    - uses: actions/checkout@v4
    
    - name: Select Xcode
      run: sudo xcode-select -s /Applications/Xcode_16.2.app
      
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v

  test-ubuntu:
    name: Test on Ubuntu
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift: ['6.0', '6.0.1', '6.0.2', '6.0.3']
        ubuntu: ['22.04', '24.04']
    container:
      image: swift:${{ matrix.swift }}-${{ matrix.ubuntu }}
    steps:
    - uses: actions/checkout@v4
    
    - name: Swift version
      run: swift --version
      
    - name: Build
      run: swift build -v
      
    - name: Run tests
      run: swift test -v

  lint:
    name: Swift Format
    runs-on: ubuntu-latest
    container:
      image: swift:latest
    steps:
    - uses: actions/checkout@v4
    
    - name: Install swift-format
      run: |
        git clone https://github.com/swiftlang/swift-format.git
        cd swift-format
        swift build -c release
        cp .build/release/swift-format /usr/local/bin/
        
    - name: Format check
      run: |
        swift-format lint -r Sources/ Tests/ || true